---
be_servers:
  ips:
    - 10.156.0.50
    - 10.156.0.51
  port: 8080


fe_servers:
  ips:
    - 10.156.0.40
    - 10.156.0.41

lb_be:
  ip: 10.156.0.30
  external_ip: 34.89.229.73

lb_fe:
  ip: 10.156.0.20

database:
  ip: 10.156.0.15
  credentials: /home/vova/devops/credentials/db_credentials_eschool.yaml

gcp:
  project_key: /home/vova/.gcloud/test1-7b663e3daccc.json
  project_id: test1-286117

ssh:
  user: vova
  key: /home/vova/.ssh/id_rsa

other:
  circleci_tocken: /home/vova/.circlecitoken
